CREATE INDEX IX_OPORTUNIDADES_ESTADO
ON OPORTUNIDADES(estado);
GO

CREATE INDEX IX_OPORTUNIDADES_GERENTE
ON OPORTUNIDADES(id_gerente);
GO

CREATE INDEX IX_ACTIVIDADES_RESPONSABLE
ON ACTIVIDADES(id_responsable);
GO
